version: "3"

services:

  mongo:
    container_name: "bib_mongo"
    user: "${UID}:${GID}"
    image: "mongo:3"
    ports:
      - "27017:27017"
    volumes:
      - "./db/mongo:/data/db"
      - /data/configdb

  redis:
    container_name: "bib_redis"
    user: "${UID}:${GID}"
    image: "redis:4"
    ports:
      - "6379:6379"
    volumes:
      - "./db/redis:/data"

