version: "3"

networks:
  bo:
  mongo:
  redis:

volumes:
  mongodata:
    driver: local
  redisdata:
    driver: local
  logos:
    driver: local

services:
  fo:
    build: 
      context: .
      dockerfile: ./app/Dockerfile
    image: sciencespo/cartoscpo-fo:prod
    env_file:
      - docker-config.env
    ports:
      - 80:80
    networks:
      - bo
    links:
      - bo:bo
    volumes:
      - logos:/cartoscpo/app/img/logos
  bo:
    build:
       context: .
       dockerfile: ./Dockerfile
       args:
         - FRONT_OFFICE_BASEURL=http://localhost
    image: sciencespo/cartoscpo-bo:prod
    env_file:
      - docker-config.env
    environment:
      - SERVER_PORT=42000
      - SERVER_HOST=localhost
      - MONGO_URI=mongodb://mongo:27017/bobib
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    networks:
      - bo
      - mongo
      - redis
    links:
      - mongo:mongo
      - redis:redis
    volumes:
      - logos:/cartoscpo/app/img/logos

  mongo:
    image: "mongo:3.6.3"
    volumes:
      - mongodata:/data/db
    networks:
      - mongo

  redis:
    image: "redis:4.0.9"
    volumes:
      - redisdata:/data
    networks:
      - redis

