[server]
port = 42000
# used to generate links in emails
host = "http://localhost"

# password hashing
salt = "YOLO"

# express session
secret = "YOLO"

# default account the first time the app is launched
adminEmail = "admin@admin"
adminPassword = "admin"

# store centers, modifications and users
[mongo]
uri = "mongodb://localhost:27017/bobib"

# store sessions
[redis]
port = 6379
host = "localhost"

[mailer]
logger = true
from = "no-reply@bobib"
#[mailer.transport]
#service = "Gmail"
#[mailer.transport.auth]
#user = "username@gmail.com"
#pass = "password"
