#!/usr/bin/env bash

if [ "$DOCKER_TAG" = "prod" ]; then
	FRONT_OFFICE_BASEURL="https://cartosciencepolitique.sciencespo.fr"
elif [ "$DOCKER_TAG" = "preprod" ]; then
	FRONT_OFFICE_BASEURL="http://cartosciencepolitique-pprd.sciences-po.fr"
else
	FRONT_OFFICE_BASEURL="http://localhost"
fi

docker build --no-cache --tag ${IMAGE_NAME} \
    --file ${BUILD_PATH} \
	--build-arg FRONT_OFFICE_BASEURL=$FRONT_OFFICE_BASEURL \
	.
